#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Scaffold the canonical alignment_baseline_v1 output tree (idempotent).

Creates the directory structure + README + report placeholder + manifest_sources
+ resolved_config_summary so the layout exists before the run. Re-runnable; never
overwrites baseline_v1. The real tables/figures/report are filled by
scripts/summarize_alignment_results.py after the training jobs finish.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.config import load_config, save_config  # noqa: E402

README = """# alignment_baseline_v1 — Step 2 no-learning adaptation baseline

Unsupervised **test-time alignment** baseline (NO target labels, NO weight learning
on target). The model trains only on the source session(s); the target session is
used only through its UNLABELED X for alignment statistics; `y_test` is used only
for the final evaluation. No `optimizer.step` on the target (only BatchNorm
running-stat updates for `bn_statistics_adaptation`).

## Methods
- `none_reference` — no alignment; **referenced** from baseline_v1 cross rows (not re-run).
- `session_zscore` — per-channel mean/std normalization.
- `euclidean_alignment` — whiten by `R^{-1/2}`, R = arithmetic mean of trial covariances
  (eigh inverse-sqrt; eps ridge + diagonal shrinkage). Matrix is 58×58.
- `riemannian_alignment` — whiten by `G^{-1/2}`, G = **log-Euclidean** SPD mean
  `expm(mean_i logm(C_i))` (numpy/scipy only; pyriemann is detected but never required).
- `bn_statistics_adaptation` — train on source, then forward unlabeled target X to
  refresh BatchNorm running mean/var only (no loss/backward/optimizer).
- `filterbank_reweighting` — θ/μ/β/low-γ FIR sub-bands; reweight each band (scalar gain,
  clipped) so the target band-power profile matches the source profile.

## Protocols
- single-source directed pairs (ses-i → ses-j, both ok).
- multi-source ses-01+ses-02 → ses-03 (all three ok).

## Models / seeds
- EEGNet / DeepConvNet / FBCNet; seeds 0–4.

## Layout
```
alignment_baseline_v1/
├── README.md
├── ALIGNMENT_BASELINE_REPORT.md      # filled by summarizer
├── RUN_STATUS.md                     # filled by summarizer
├── manifest_sources.json
├── resolved_config_summary.yaml
├── full_job_ids.txt                  # training job ids (E)
└── cross_session/
    ├── runs/      # per-(method,model,scope,seed) result CSVs (+ meta json)
    ├── splits/    # per-(task,seed) split JSON (train/val idx, sessions)
    ├── tables/    # results_alignment_all.csv + aggregates (summarizer)
    └── figures/   # comparison/gain figures (summarizer)
```

Do NOT overwrite `baseline_v1/`. `none_reference` is read from
`outputs/experiments/baseline_v1/cross_session/tables/results_cross_session_all.csv`.
"""

REPORT_PLACEHOLDER = """# Alignment Baseline (Step 2) — Report

**STATUS: PENDING.** Training jobs submitted; this report is generated by
`scripts/summarize_alignment_results.py` (dependent CPU job) after all training
jobs finish. Until then, see `RUN_STATUS.md` and `full_job_ids.txt`.
"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Scaffold alignment_baseline_v1 outputs.")
    ap.add_argument("--out", default="outputs/experiments/alignment_baseline_v1")
    ap.add_argument("--config", default="configs/session_alignment_compare.yaml")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir = out_dir if out_dir.is_absolute() else PROJECT_ROOT / out_dir
    cross = out_dir / "cross_session"
    for sub in ["runs", "splits", "tables", "figures"]:
        (cross / sub).mkdir(parents=True, exist_ok=True)

    (out_dir / "README.md").write_text(README, encoding="utf-8")
    if not (out_dir / "ALIGNMENT_BASELINE_REPORT.md").exists():
        (out_dir / "ALIGNMENT_BASELINE_REPORT.md").write_text(REPORT_PLACEHOLDER, encoding="utf-8")

    cfg = load_config(PROJECT_ROOT / args.config)
    save_config(cfg, out_dir / "resolved_config_summary.yaml")

    manifest = {
        "experiment_id": "alignment_baseline_v1",
        "status": "scaffolded",
        "config": str(args.config),
        "baseline_none_reference_source":
            "outputs/experiments/baseline_v1/cross_session/tables/results_cross_session_all.csv",
        "drift_levels_source": "outputs/analysis/session_drift_v1/per_subject_drift_summary.csv",
        "methods": cfg.get("methods", []),
        "models": cfg.get("models", []),
        "seeds": cfg.get("train", {}).get("seeds", []),
        "protocols": cfg.get("protocols", []),
    }
    (out_dir / "manifest_sources.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2),
                                                   encoding="utf-8")
    print(f"[scaffold] alignment_baseline_v1 tree ready at {out_dir}")


if __name__ == "__main__":
    main()
